

server:
  port: 8001

  spring:
    application:
      name: test-post-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


#actuator
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info, shutdown
  endpoint:
    shutdown:
      enabled: true